spring:
  config:
    activate:
      on-profile: 'local'
  redis:
    host: 'localhost'
    port: 16379
  data:
    mongodb:
      host: 'localhost'
      port: 37017
      database: 'local'
      username:
      password: