spring:
  config:
    activate:
      on-profile: 'alpha'
  redis:
    host: 'localhost'
    port: 6379
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'alpha'
      username:
      password: